---
runtime: python39
env_variables:
  DATABASE_URL: postgresql+psycopg2://checkappsql:X'Y*?#F[Gj3o2ijQ@/checkappsql?host=/cloudsql/checkingapp-427312:us-central1:checkapp
  SECRET_KEY: 91581L2#sg
  CLOUD_SQL_CONNECTION_NAME: checkingapp-427312:us-central1:checkapp
entrypoint: gunicorn -b :$PORT app:app
handlers:
  - url: /static*
    static_dir: www
  - url: /.*
    secure: optional
    redirect_http_response_code: 301
    script: auto
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1  
# - url: /static/images  
# - url: /static/js
#   static_dir: www/js
#   static_dir: www/images